[package]
name = "cu-automotive-payloads"
description = "Standardized automotive payload definitions for CAN, CAN FD, ISO-TP, UDS, and SOME/IP protocols — Copper project."
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
cu29 = { path = "../../../core/cu29", version = "1.0.0-rc2", default-features = false }
cu29-clock = { path = "../../../core/cu29_clock", version = "1.0.0-rc2", default-features = false }
serde = { workspace = true }
serde-big-array = { version = "0.5", default-features = false }

[features]
default = ["std", "reflect"]
std = ["cu29/std", "cu29-clock/std"]
textlogs = ["cu29/textlogs"]
reflect = ["cu29/reflect", "cu29-clock/reflect"]
